(function(){
 const $=id=>document.getElementById(id);
 const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
 const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 window.openRoflixTools=function(which){
  const modal=$('roflix-tools-modal'), box=$('roflix-tools-content'), title=$('roflix-tools-title'); modal.style.display='block';
  if(which==='sync'){
   title.textContent='🔄 Đồng bộ xem tiếp giữa thiết bị';
   const payload={version:1,updatedAt:new Date().toISOString(),history:((typeof getWatchHistory === 'function') ? getWatchHistory() : []),favorites:read('roflix-favorites',[]),collections:read('roflix-collections',[]),profiles:read('roflix-profiles',[])};
   box.innerHTML=`<p style="color:#cbd5e1;margin-bottom:12px">Bản HTML tĩnh chưa có máy chủ đồng bộ đám mây. Bạn có thể chuyển dữ liệu an toàn giữa máy bằng mã JSON: xuất trên máy cũ, gửi riêng cho mình, rồi nhập trên máy mới.</p><button class="bg-amber-500 text-black font-bold rounded-xl px-4 py-3" onclick="exportRoFlixSync()">Xuất mã đồng bộ</button><textarea id="roflix-sync-data" rows="7" placeholder="Dán mã đồng bộ vào đây trên thiết bị mới" style="display:block;width:100%;margin:14px 0;background:#080a12;border:1px solid #444;padding:12px;border-radius:12px;color:white"></textarea><button class="bg-emerald-600 font-bold rounded-xl px-4 py-3" onclick="importRoFlixSync()">Nhập / hợp nhất dữ liệu</button><p id="roflix-sync-msg" style="margin-top:12px;color:#a7f3d0"></p>`;
  } else if(which==='collections'){
   title.textContent='📚 Bộ sưu tập cá nhân';
   box.innerHTML=`<p style="color:#cbd5e1;margin-bottom:12px">Tạo nhiều bộ sưu tập và thêm phim bằng slug phim (đường dẫn API). Dữ liệu lưu trên trình duyệt hiện tại.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><input id="rf-col-name" placeholder="Tên bộ sưu tập" style="flex:1;min-width:160px;background:#080a12;border:1px solid #444;padding:12px;border-radius:10px;color:white"><button onclick="createRfCollection()" class="bg-amber-500 text-black font-bold rounded-xl px-4">Tạo</button></div><div id="rf-cols" style="margin-top:16px"></div>`; renderRfCollections();
  } else if(which==='community'){
   title.textContent='💬 Cộng đồng RoFlix';
   box.innerHTML=`<p style="color:#cbd5e1;margin-bottom:12px">Review và bình luận được lưu cục bộ trên trình duyệt này. Để hiển thị đa người dùng cần triển khai API cộng đồng và cơ sở dữ liệu.</p><input id="rf-community-movie" placeholder="Tên phim hoặc slug" style="width:100%;background:#080a12;border:1px solid #444;padding:12px;border-radius:10px;color:white;margin-bottom:10px"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><label style="color:#cbd5e1">Đánh giá <select id="rf-community-rating" style="background:#080a12;padding:8px;border-radius:8px;color:white"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select> / 5</label><input id="rf-community-user" placeholder="Tên hiển thị" style="flex:1;min-width:130px;background:#080a12;border:1px solid #444;padding:10px;border-radius:10px;color:white"></div><textarea id="rf-community-text" rows="3" placeholder="Viết review hoặc bình luận..." style="width:100%;background:#080a12;border:1px solid #444;padding:12px;border-radius:10px;color:white;margin:10px 0"></textarea><button onclick="rfPostCommunity()" class="bg-amber-500 text-black font-bold rounded-xl px-4 py-3">Đăng bài</button><div id="rf-community-feed" style="margin-top:16px"></div>`;renderRfCommunity();
  } else if(which==='party'){
   title.textContent='🎬 Xem chung realtime';
   box.innerHTML=`<p style="color:#cbd5e1;margin-bottom:12px">Tạo phòng xem chung bằng Supabase Realtime. Thành viên, phim, tập và chat được cập nhật realtime.</p><input id="rf-party-title" placeholder="Tên phòng / phim" value="${escRf(window.currentMovieTitle||'')}" style="width:100%;background:#080a12;border:1px solid #444;padding:12px;border-radius:10px;color:white;margin:12px 0"><div style="display:flex;gap:8px;flex-wrap:wrap"><button onclick="rfWatchPartyCreate()" class="bg-amber-500 text-black font-bold rounded-xl px-4 py-3">🎬 Tạo phòng realtime</button><button onclick="rfWatchPartySyncNow()" class="bg-blue-700 rounded-xl px-4 py-3">🔄 Đồng bộ ngay</button><button onclick="rfWatchPartyLeave()" class="bg-gray-700 rounded-xl px-4 py-3">🚪 Rời phòng</button></div><div id="rf-party-result" style="margin-top:16px;color:#d1fae5"></div><div id="rf-party-members" style="margin-top:10px"></div><div class="rf-party-chat"><div class="rf-party-chat-title">💬 Chat phòng</div><div id="rf-party-chat-list" class="rf-party-chat-list"></div><div class="rf-party-chat-compose"><input id="rf-party-chat-input" placeholder="Nhắn gì đó..." maxlength="500" onkeydown="if(event.key==='Enter')rfWatchPartySendChat()"><button onclick="rfWatchPartySendChat()">Gửi</button></div></div><hr style="border-color:#333;margin:18px 0"><input id="rf-party-join" placeholder="Nhập mã phòng, ví dụ RF-ABCDE" style="width:100%;background:#080a12;border:1px solid #444;padding:12px;border-radius:10px;color:white;margin-bottom:10px"><button onclick="rfWatchPartyJoin()" class="bg-emerald-700 rounded-xl px-4 py-3">🔗 Tham gia phòng</button><div id="rf-party-status" style="margin-top:12px;color:#cbd5e1"></div><p style="color:#9ca3af;font-size:12px;margin-top:12px">Lưu ý: iframe nguồn phim bên ngoài không cho RoFlix điều khiển thanh thời gian nội bộ. Bản nâng cấp đồng bộ phòng, thành viên, phim, tập và chat realtime.</p>`;
  } else if(which==='calendar'){
   title.textContent='🗓️ Lịch phim & nhắc tập mới';
   box.innerHTML=`<p style="color:#cbd5e1">Thêm lịch nhắc thủ công cho phim đang theo dõi. Thông báo tập mới tự động cần nguồn API lịch phát hành ổn định và tác vụ máy chủ.</p><div style="display:grid;gap:10px;margin-top:12px"><input id="rf-cal-title" placeholder="Tên phim / tập" style="background:#080a12;border:1px solid #444;padding:12px;border-radius:10px;color:white"><input id="rf-cal-date" type="datetime-local" style="background:#080a12;border:1px solid #444;padding:12px;border-radius:10px;color:white"><button onclick="rfAddCalendar()" class="bg-amber-500 text-black font-bold rounded-xl px-4 py-3">Thêm lịch nhắc</button></div><div id="rf-calendar-list" style="margin-top:16px"></div>`;renderRfCalendar();
  } else if(which==='admin'){
   window.location.href='admin.html';
   return;
  } else if(which==='__legacy_admin_removed__'){
   title.textContent='🛠️ Bảng quản trị cục bộ';
   box.innerHTML=`<p style="color:#cbd5e1">Bảng thống kê trên trình duyệt này, không phải hệ thống quản trị máy chủ. Mật khẩu phía client không thể bảo vệ dữ liệu khi phát hành công khai.</p><div id="rf-admin-stats" class="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-4"></div><div class="mt-4 flex gap-2 flex-wrap"><button onclick="downloadRfAdminReport()" class="bg-amber-500 text-black font-bold rounded-xl px-4 py-3">Xuất báo cáo JSON</button><button onclick="clearRfLocalCache()" class="bg-red-700 font-bold rounded-xl px-4 py-3">Xóa cache RoFlix cục bộ</button></div><p id="rf-admin-note" style="margin-top:12px;color:#fca5a5"></p>`; renderRfAdmin();
  }
 };
 window.rfPostCommunity=function(){const movie=$('rf-community-movie').value.trim(),body=$('rf-community-text').value.trim();if(!movie||!body){alert('Nhập tên phim và nội dung trước khi đăng.');return;}const a=read('roflix-community-posts',[]);a.unshift({id:'p'+Date.now(),movie,user:$('rf-community-user').value.trim()||'Khách RoFlix',rating:Number($('rf-community-rating').value)||5,body,createdAt:new Date().toISOString(),status:'visible'});write('roflix-community-posts',a);$('rf-community-text').value='';renderRfCommunity();};
 window.renderRfCommunity=function(){const el=$('rf-community-feed');if(!el)return;const a=read('roflix-community-posts',[]);el.innerHTML=a.length?a.map(p=>`<article style="background:#1b1d2b;border:1px solid #37394a;border-radius:12px;padding:14px;margin:9px 0"><div style="display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap"><b>${escRf(p.movie)}</b><span style="color:#fbbf24">${'★'.repeat(Math.max(1,Math.min(5,p.rating||5)))}${'☆'.repeat(5-Math.max(1,Math.min(5,p.rating||5)))}</span></div><small style="color:#9ca3af">${escRf(p.user)} · ${new Date(p.createdAt).toLocaleString()}</small><p style="color:#e5e7eb;margin-top:8px;white-space:pre-wrap">${escRf(p.body)}</p><button onclick="rfDeleteCommunity('${p.id}')" style="color:#fca5a5;font-size:12px;margin-top:6px">Xóa bài trên thiết bị này</button></article>`).join(''):'<p style="color:#9ca3af">Chưa có bài review. Hãy đăng bài đầu tiên!</p>';};window.rfDeleteCommunity=function(id){write('roflix-community-posts',read('roflix-community-posts',[]).filter(p=>p.id!==id));renderRfCommunity();};
 window.rfCreateParty=window.rfWatchPartyCreate;
 window.rfJoinParty=window.rfWatchPartyJoin;
 window.rfAddCalendar=function(){const title=$('rf-cal-title').value.trim(),date=$('rf-cal-date').value;if(!title||!date){alert('Nhập tên phim và ngày giờ.');return;}const a=read('roflix-release-calendar',[]);a.push({id:'cal'+Date.now(),title,date,notified:false});write('roflix-release-calendar',a);$('rf-cal-title').value='';renderRfCalendar();};window.renderRfCalendar=function(){const el=$('rf-calendar-list');if(!el)return;const a=read('roflix-release-calendar',[]).sort((x,y)=>new Date(x.date)-new Date(y.date));el.innerHTML=a.length?a.map(x=>`<div style="background:#1b1d2b;border-radius:12px;padding:12px;margin:8px 0;display:flex;justify-content:space-between;gap:10px"><div><b>${escRf(x.title)}</b><div style="color:#9ca3af;font-size:12px">${new Date(x.date).toLocaleString()}</div></div><button onclick="rfRemoveCalendar('${x.id}')" style="color:#fca5a5">Xóa</button></div>`).join(''):'<p style="color:#9ca3af">Chưa có lịch nhắc.</p>';};window.rfRemoveCalendar=function(id){write('roflix-release-calendar',read('roflix-release-calendar',[]).filter(x=>x.id!==id));renderRfCalendar();};
 window.closeRoflixTools=()=>{$('roflix-tools-modal').style.display='none'};
 window.exportRoFlixSync=function(){const data={version:1,updatedAt:new Date().toISOString(),history:((typeof getWatchHistory === 'function') ? getWatchHistory() : []),favorites:read('roflix-favorites',[]),collections:read('roflix-collections',[]),profiles:read('roflix-profiles',[])};$('roflix-sync-data').value=btoa(unescape(encodeURIComponent(JSON.stringify(data))));$('roflix-sync-msg').textContent='Đã tạo mã. Sao chép toàn bộ mã để nhập trên thiết bị khác.';};
 window.importRoFlixSync=function(){try{const d=JSON.parse(decodeURIComponent(escape(atob($('roflix-sync-data').value.trim()))));if(d.version!==1)throw Error('Phiên bản mã không được hỗ trợ');for(const k of ['history','favorites','collections','profiles']){if(Array.isArray(d[k])){const old=read('roflix-'+(k==='history'?'watch-history':k),[]);const merged=[...old,...d[k]];const key=k==='history'?'slug':(k==='collections'?'id':null);const unique=key?[...new Map(merged.map(x=>[x[key]||JSON.stringify(x),x])).values()]:merged;if(k==='history' && typeof getWatchHistoryStorageKey==='function'){const hk=getWatchHistoryStorageKey();if(hk)localStorage.setItem(hk,JSON.stringify(unique));}else write('roflix-'+(k==='history'?'watch-history':k),unique);}}$('roflix-sync-msg').textContent='Nhập dữ liệu thành công. Tải lại trang để cập nhật giao diện.';}catch(e){$('roflix-sync-msg').textContent='Mã không hợp lệ hoặc bị lỗi.';}};
 window.createRfCollection=function(){const name=$('rf-col-name').value.trim();if(!name)return;const a=read('roflix-collections',[]);a.push({id:'c'+Date.now(),name,items:[],createdAt:Date.now()});write('roflix-collections',a);$('rf-col-name').value='';renderRfCollections();};
 window.renderRfCollections=function(){const a=read('roflix-collections',[]);const el=$('rf-cols');if(!el)return;el.innerHTML=a.length?a.map(c=>`<div style="background:#1b1d2b;border:1px solid #37394a;border-radius:12px;padding:14px;margin:8px 0"><b>${escRf(c.name)}</b><p style="color:#9ca3af;font-size:12px;margin:5px 0">${(c.items||[]).length} phim</p><div style="display:flex;gap:8px;flex-wrap:wrap"><input id="rf-slug-${c.id}" placeholder="Slug phim" style="background:#080a12;border:1px solid #444;padding:8px;border-radius:8px;color:white"><button onclick="addRfMovie('${c.id}')" class="bg-amber-500 text-black rounded-lg px-3">Thêm phim</button><button onclick="deleteRfCollection('${c.id}')" class="bg-red-700 rounded-lg px-3">Xóa bộ</button></div><div style="color:#cbd5e1;font-size:12px;margin-top:8px">${(c.items||[]).map(escRf).join(' · ')||'Chưa có phim'}</div></div>`).join(''):'<p style="color:#9ca3af">Chưa có bộ sưu tập nào.</p>';};
 window.addRfMovie=function(id){const slug=$('rf-slug-'+id).value.trim();if(!slug)return;const a=read('roflix-collections',[]),c=a.find(x=>x.id===id);if(c&&!c.items.includes(slug))c.items.push(slug);write('roflix-collections',a);renderRfCollections();};window.deleteRfCollection=function(id){write('roflix-collections',read('roflix-collections',[]).filter(x=>x.id!==id));renderRfCollections();};
 function renderRfAdmin(){const el=$('rf-admin-stats');if(!el)return;const h=((typeof getWatchHistory === 'function') ? getWatchHistory() : []),f=read('roflix-favorites',[]),c=read('roflix-collections',[]),p=read('roflix-community-posts',[]),r=read('roflix-party-rooms',[]),cal=read('roflix-release-calendar',[]);el.innerHTML=[['Lịch sử xem',h.length],['Yêu thích',f.length],['Bộ sưu tập',c.length],['Review/bình luận',p.length],['Phòng đã tạo',r.length],['Lịch nhắc',cal.length]].map(x=>`<div style="background:#1b1d2b;border-radius:14px;padding:18px"><div style="color:#9ca3af">${x[0]}</div><div style="font-size:30px;font-weight:800;color:#fbbf24">${x[1]}</div></div>`).join('');}
 window.downloadRfAdminReport=function(){const data={generatedAt:new Date().toISOString(),history:((typeof getWatchHistory === 'function') ? getWatchHistory() : []),favorites:read('roflix-favorites',[]),collections:read('roflix-collections',[]),community:read('roflix-community-posts',[]),partyRooms:read('roflix-party-rooms',[]),calendar:read('roflix-release-calendar',[])};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='roflix-admin-report.json';a.click();URL.revokeObjectURL(a.href);};
 window.clearRfLocalCache=function(){if(!confirm('Xóa cache phim cục bộ? Không xóa tài khoản và lịch sử xem.'))return;Object.keys(localStorage).filter(k=>/^roflix-(cache|api-cache)/i.test(k)).forEach(k=>localStorage.removeItem(k));$('rf-admin-note').textContent='Đã xóa các mục cache có tiền tố roflix-cache / roflix-api-cache nếu có.';};
 function escRf(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 // Player enhancement: provide persistent next-episode control; embedded providers may block playback-end events.
 document.addEventListener('DOMContentLoaded',()=>{const player=$('movie-player');if(!player)return;const host=player.parentElement;if(!host||$('rf-player-controls'))return;const bar=document.createElement('div');bar.id='rf-player-controls';bar.style.cssText='display:flex;gap:10px;flex-wrap:wrap;margin:12px 0';bar.innerHTML='<button onclick="rfPrevEpisode()" class="bg-gray-700 rounded-xl px-4 py-3">⏮ Tập trước</button><button onclick="rfNextEpisode()" class="bg-amber-500 text-black font-bold rounded-xl px-4 py-3">Tập tiếp theo ⏭</button><label style="display:flex;align-items:center;gap:8px;color:#cbd5e1"><input id="rf-auto-next" type="checkbox" checked> Tự chuyển tập (nếu trình phát cho phép)</label>';player.insertAdjacentElement('afterend',bar);});
 window.rfNextEpisode=function(){const i=(window.currentEpisodeList||[]).findIndex(e=>e.link===$('movie-player')?.src);if(i>=0&&i<currentEpisodeList.length-1)playMovieByIndex(i+1);else if(currentEpisodeList.length>1)playMovieByIndex(Math.min(currentEpisodeList.length-1,(window.rfLastEpisodeIndex||0)+1));};window.rfPrevEpisode=function(){const i=(window.currentEpisodeList||[]).findIndex(e=>e.link===$('movie-player')?.src);playMovieByIndex(Math.max(0,i-1));};
})();
