/* RoFlix Pro V2 UI enhancements + All Features 2.0 loader */
(function(){'use strict';const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const sourceName=sid=>sid==='vsmov'?'VSMOV':'KKPhim';
 function renderRecoCards(id,movies){const el=document.getElementById(id);if(!el)return;if(!movies?.length){el.innerHTML='<div class="rf-empty-state">Chưa có đề xuất phù hợp.</div>';return}el.innerHTML=movies.slice(0,10).map(m=>`<article class="rf-reco-card" onclick="viewMovieDetail('${String(m.slug||'').replace(/'/g,"\\'")}','${m._src||''}')"><div class="rf-reco-poster"><img src="${esc(m.poster)}" alt="${esc(m.title)}" loading="lazy" onerror="this.src='https://placehold.co/220x330/10131d/f59e0b?text=RoFlix'"><span class="rf-reco-play"><i class="fa-solid fa-play"></i></span></div><div class="rf-reco-body"><h4>${esc(m.title)}</h4><p><i class="fa-solid fa-star"></i> ${esc(m.rating||'N/A')} · ${esc(m.year||'')}</p><button type="button" onclick="event.stopPropagation(); playMovie('${String(m.slug||'').replace(/'/g,"\\'")}','${m._src||''}')">Xem phim</button></div></article>`).join('')}
 async function reco(exclude){try{if(typeof fetchRecoPool!=='function')return[];const pool=await fetchRecoPool(),sig=typeof getRecoSignals==='function'?getRecoSignals():{watched:new Set()};return pool.filter(m=>m.slug&&m.slug!==exclude).map(m=>({m,score:typeof scoreMovie==='function'?scoreMovie(m,sig):(parseFloat(m.rating)||0)})).sort((a,b)=>b.score-a.score).map(x=>x.m).filter(m=>!sig.watched?.has?.(m.slug))}catch(e){console.debug('[RoFlix V2]',e);return[]}}
 async function detailReco(){const slug=window.currentSlug||'',row=document.getElementById('detail-reco-row');if(!row)return;row.innerHTML='<div class="rf-loading-line">Đang tìm phim bạn có thể thích...</div>';renderRecoCards('detail-reco-row',await reco(slug))}
 async function playerReco(){const slug=window.currentSlug||'',row=document.getElementById('play-reco-row');if(!row)return;row.innerHTML='<div class="rf-loading-line">Đang tìm phim bạn có thể xem tiếp...</div>';renderRecoCards('play-reco-row',await reco(slug))}
 function meta(){const m=window.currentMovieData||{};const a=document.getElementById('playing-title'),b=document.getElementById('playing-origin'),c=document.getElementById('playing-summary'),d=document.getElementById('playing-source'),e=document.getElementById('playing-poster');if(a&&m.title)a.textContent=m.title;if(b)b.textContent=m.origin_name||'';if(c)c.textContent=m.summary||'Chưa có tóm tắt cho phim này.';if(d)d.textContent=sourceName(m._src||window.currentSourceId);if(e){e.src=m.poster||'';e.alt=m.title||'RoFlix'}}
 function globals(){try{if(!Object.prototype.hasOwnProperty.call(window,'currentSlug'))Object.defineProperty(window,'currentSlug',{get:()=>currentSlug});if(!Object.prototype.hasOwnProperty.call(window,'currentMovieData'))Object.defineProperty(window,'currentMovieData',{get:()=>currentMovieData});if(!Object.prototype.hasOwnProperty.call(window,'currentSourceId'))Object.defineProperty(window,'currentSourceId',{get:()=>currentSourceId});if(!Object.prototype.hasOwnProperty.call(window,'currentEpisodeList'))Object.defineProperty(window,'currentEpisodeList',{get:()=>currentEpisodeList});if(!Object.prototype.hasOwnProperty.call(window,'currentMovieTitle'))Object.defineProperty(window,'currentMovieTitle',{get:()=>currentMovieTitle})}catch(_){} }
 const ov=window.viewMovieDetail;if(typeof ov==='function')window.viewMovieDetail=async function(){const r=await ov.apply(this,arguments);globals();setTimeout(detailReco,80);setTimeout(()=>window.rfRenderCommentThread2?.(window.currentSlug||''),350);return r};const op=window.playMovieByIndex;if(typeof op==='function')window.playMovieByIndex=function(){const r=op.apply(this,arguments);setTimeout(()=>{meta();playerReco();window.rfMovieCommentsRender?.(window.currentSlug||currentSlug,window.currentMovieTitle||currentMovieTitle);window.rfRenderCommentThread2?.(window.currentSlug||currentSlug)},100);return r};window.rfRefreshDetailRecommendations=detailReco;window.rfRefreshPlayerRecommendations=playerReco;
 function load(id,src){if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.async=false;document.head.appendChild(s)}function css(){if(document.getElementById('roflix-movie-lock-css'))return;const l=document.createElement('link');l.id='roflix-movie-lock-css';l.rel='stylesheet';l.href='css/movie-lock-ui.css?v=2';document.head.appendChild(l)}function boot(){css();load('roflix-header-menu-script','js/features/header-hamburger.js?v=4');load('roflix-cloud-user-data-script','js/features/cloud-user-data.js?v=2');load('roflix-comments-realtime-script','js/features/comments-realtime.js?v=3');load('roflix-all-features-2-script','js/features/roflix-all-features-2.js?v=1');load('roflix-comment-reactions-2-script','js/features/comments-reactions-2.js?v=1');load('roflix-cloud-hydrate-2-script','js/features/cloud-hydrate-2.js?v=1');load('roflix-movie-control-script','js/features/movie-control-client.js?v=2');load('roflix-movie-preferred-source-script','js/features/movie-control-preferred-source.js?v=1');load('roflix-movie-lock-ui-script','js/features/movie-lock-ui.js?v=2')}
 function pwa(){if(!('serviceWorker'in navigator))return;window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js',{scope:'/'}).catch(e=>console.debug('[RoFlix PWA]',e)),{once:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();pwa();})();
