(function(){
 const sb=window.rfSupabase;
 if(!sb){console.error('[RoFlix] rfSupabase chưa được khởi tạo.');return;}
 const $=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const status=(id,msg,color='#cbd5e1')=>{const e=$(id);if(e){e.textContent=msg;e.style.color=color;}};
 async function user(){const {data}=await sb.auth.getUser();return data?.user||null;}
 async function authBox(target){const u=await user();const el=$(target);if(!el)return;
  if(u){el.innerHTML=`<div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;background:#181a27;padding:12px;border-radius:12px"><span>Đăng nhập: <b>${esc(u.email)}</b></span><button id="rf-cloud-logout" class="bg-gray-700 rounded-lg px-3 py-2">Đăng xuất</button></div>`;
   $('rf-cloud-logout').onclick=async()=>{await sb.auth.signOut();await authBox(target);if(target==='rf-auth-admin')await renderAdmin();if(target==='rf-auth-community')await renderCommunity();};
  }else{el.innerHTML=`<div style="background:#181a27;padding:14px;border-radius:12px"><b>Đăng nhập / tạo tài khoản RoFlix</b><div style="display:grid;gap:9px;margin-top:10px"><input id="rf-auth-email" type="email" placeholder="Email" style="background:#080a12;border:1px solid #444;padding:11px;border-radius:9px;color:white"><input id="rf-auth-password" type="password" placeholder="Mật khẩu (ít nhất 6 ký tự)" style="background:#080a12;border:1px solid #444;padding:11px;border-radius:9px;color:white"><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="rf-auth-login" class="bg-emerald-700 rounded-lg px-4 py-2">Đăng nhập</button><button id="rf-auth-signup" class="bg-gray-700 rounded-lg px-4 py-2">Tạo tài khoản</button></div><small id="rf-auth-msg" style="color:#fbbf24"></small></div></div>`;
   const run=async signup=>{const email=$('rf-auth-email').value.trim(),password=$('rf-auth-password').value;if(!email||password.length<6){status('rf-auth-msg','Nhập email và mật khẩu tối thiểu 6 ký tự.','#fca5a5');return;}const res=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(res.error){status('rf-auth-msg',res.error.message,'#fca5a5');return;}status('rf-auth-msg',signup?'Đã gửi yêu cầu tạo tài khoản. Nếu yêu cầu xác minh email, hãy kiểm tra hộp thư.':'Đăng nhập thành công.','#86efac');await authBox(target);if(target==='rf-auth-community')await renderCommunity();if(target==='rf-auth-admin')await renderAdmin();};
   $('rf-auth-login').onclick=()=>run(false);$('rf-auth-signup').onclick=()=>run(true);
  }
 }
 async function renderCommunity(){const el=$('rf-community-feed');if(!el)return;const u=await user();const {data,error}=await sb.from('community_posts').select('id,movie_title,rating,body,display_name,user_id,created_at').eq('status','visible').order('created_at',{ascending:false}).limit(100);if(error){el.innerHTML=`<p style="color:#fca5a5">Không tải được bài viết: ${esc(error.message)}. Hãy chạy file SQL thiết lập Supabase đi kèm.</p>`;return;}el.innerHTML=data?.length?data.map(p=>`<article style="background:#1b1d2b;border:1px solid #37394a;border-radius:12px;padding:14px;margin:9px 0"><div style="display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap"><b>${esc(p.movie_title)}</b><span style="color:#fbbf24">${'★'.repeat(p.rating||5)}${'☆'.repeat(5-(p.rating||5))}</span></div><small style="color:#9ca3af">${esc(p.display_name||'RoFlix user')} · ${new Date(p.created_at).toLocaleString()}</small><p style="color:#e5e7eb;margin-top:8px;white-space:pre-wrap">${esc(p.body)}</p>${u&&u.id===p.user_id?`<button onclick="rfCloudDeletePost('${p.id}')" style="color:#fca5a5;font-size:12px;margin-top:6px">Xóa bài của tôi</button>`:''}</article>`).join(''):'<p style="color:#9ca3af">Chưa có bài review. Hãy đăng bài đầu tiên!</p>';}
 window.rfPostCommunity=async function(){const u=await user();if(!u){alert('Bạn cần đăng nhập để đăng bài.');return;}const movie=$('rf-community-movie')?.value.trim(),body=$('rf-community-text')?.value.trim(),rating=Number($('rf-community-rating')?.value)||5,display=($('rf-community-user')?.value.trim()||u.email?.split('@')[0]||'RoFlix user').slice(0,40);if(!movie||!body){alert('Nhập tên phim và nội dung trước khi đăng.');return;}const {error}=await sb.from('community_posts').insert({movie_title:movie.slice(0,160),body:body.slice(0,3000),rating,display_name:display,user_id:u.id});if(error){alert('Không đăng được: '+error.message);return;}$('rf-community-text').value='';await renderCommunity();};
 window.rfCloudDeletePost=async function(id){if(!confirm('Xóa bài viết này?'))return;const {error}=await sb.from('community_posts').delete().eq('id',id);if(error)alert('Không xóa được: '+error.message);else await renderCommunity();};
 async function renderAdmin(){const el=$('rf-admin-stats');if(!el)return;const u=await user();if(!u){el.innerHTML='<p style="color:#fca5a5">Hãy đăng nhập bằng tài khoản đã được cấp quyền Admin.</p>';return;}const {data:profile,error:pe}=await sb.from('profiles').select('role,display_name').eq('id',u.id).maybeSingle();if(pe){el.innerHTML=`<p style="color:#fca5a5">${esc(pe.message)}. Chạy SQL setup trước.</p>`;return;}if(profile?.role!=='admin'){el.innerHTML='<p style="color:#fca5a5">Tài khoản này chưa có quyền Admin. Hãy cấp role admin cho user ID trong Supabase SQL Editor theo hướng dẫn.</p>';return;}
 const [postsRes,usersRes,hiddenRes]=await Promise.all([sb.from('community_posts').select('id,movie_title,body,display_name,status,created_at,user_id').order('created_at',{ascending:false}).limit(200),sb.from('profiles').select('id,display_name,role,created_at').order('created_at',{ascending:false}).limit(300),sb.from('community_posts').select('id',{count:'exact',head:true}).eq('status','hidden')]);
 if(postsRes.error||usersRes.error){el.innerHTML='<p style="color:#fca5a5">Không tải được dữ liệu quản trị. Kiểm tra SQL/RLS.</p>';return;}
 el.innerHTML=`<div class="grid grid-cols-1 sm:grid-cols-3 gap-3"><div style="background:#1b1d2b;border-radius:12px;padding:16px">Người dùng<div style="font-size:28px;color:#fbbf24;font-weight:800">${usersRes.data.length}</div></div><div style="background:#1b1d2b;border-radius:12px;padding:16px">Tổng bài tải về<div style="font-size:28px;color:#fbbf24;font-weight:800">${postsRes.data.length}</div></div><div style="background:#1b1d2b;border-radius:12px;padding:16px">Bài ẩn<div style="font-size:28px;color:#fbbf24;font-weight:800">${hiddenRes.count||0}</div></div></div><h3 style="font-size:18px;font-weight:800;margin:20px 0 8px">Quản lý bài cộng đồng</h3><div>${postsRes.data.map(p=>`<article style="background:#1b1d2b;border:1px solid #37394a;border-radius:12px;padding:12px;margin:8px 0"><b>${esc(p.movie_title)}</b> <span style="color:#9ca3af">· ${esc(p.display_name)} · ${esc(p.status)}</span><p style="margin:6px 0;color:#cbd5e1">${esc(p.body).slice(0,350)}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="bg-gray-700 rounded-lg px-3 py-2" onclick="rfAdminSetPost('${p.id}','${p.status==='visible'?'hidden':'visible'}')">${p.status==='visible'?'Ẩn bài':'Hiện bài'}</button><button class="bg-red-800 rounded-lg px-3 py-2" onclick="rfAdminDeletePost('${p.id}')">Xóa vĩnh viễn</button></div></article>`).join('')||'<p>Chưa có bài viết.</p>'}</div><h3 style="font-size:18px;font-weight:800;margin:20px 0 8px">Quản lý vai trò</h3><p style="color:#9ca3af;font-size:13px">Chỉ Admin hiện tại mới có thể thay đổi vai trò. Không cấp admin cho người không đáng tin cậy.</p><div>${usersRes.data.map(x=>`<div style="display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap;background:#1b1d2b;border-radius:10px;padding:10px;margin:6px 0"><span>${esc(x.display_name||x.id.slice(0,8))} · <small>${esc(x.role||'user')}</small></span><select id="rf-role-${x.id}" style="background:#080a12;color:white;padding:8px;border-radius:8px"><option value="user" ${x.role==='user'?'selected':''}>user</option><option value="admin" ${x.role==='admin'?'selected':''}>admin</option></select><button class="bg-gray-700 rounded-lg px-3 py-2" onclick="rfAdminSetRole('${x.id}')">Lưu vai trò</button></div>`).join('')}</div>`;
 }
 window.rfAdminSetPost=async(id,statusVal)=>{const {error}=await sb.from('community_posts').update({status:statusVal}).eq('id',id);if(error)alert(error.message);else renderAdmin();};
 window.rfAdminDeletePost=async id=>{if(!confirm('Xóa vĩnh viễn bài này?'))return;const {error}=await sb.from('community_posts').delete().eq('id',id);if(error)alert(error.message);else renderAdmin();};
 window.rfAdminSetRole=async id=>{const role=$('rf-role-'+id)?.value;if(!role)return;if(!confirm('Thay đổi quyền người dùng thành '+role+'?'))return;const {error}=await sb.from('profiles').update({role}).eq('id',id);if(error)alert('Không đổi được vai trò: '+error.message);else{alert('Đã cập nhật vai trò.');renderAdmin();}};
 const originalOpen=window.openRoflixTools;
 window.openRoflixTools=function(which){originalOpen(which);if(which==='community'){const box=$('roflix-tools-content');box.insertAdjacentHTML('afterbegin','<div id="rf-auth-community" style="margin-bottom:14px"></div><div style="color:#9ca3af;font-size:12px;margin-bottom:10px">Bài đăng được chia sẻ qua Supabase với người dùng khác. Cần đăng nhập để đăng bài.</div>');authBox('rf-auth-community').then(renderCommunity);}else if(which==='admin'){window.location.href='admin.html';return;}};
 sb.auth.onAuthStateChange(()=>{if($('rf-auth-community')){authBox('rf-auth-community').then(renderCommunity);}if($('rf-auth-admin')){authBox('rf-auth-admin').then(renderAdmin);}});
 const loadCloudCenter=()=>{if(document.getElementById('rf-cloud-center-script'))return;const s=document.createElement('script');s.id='rf-cloud-center-script';s.src='js/features/cloud-center.js';s.async=true;document.head.appendChild(s)};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadCloudCenter,{once:true});else loadCloudCenter();
})();
