-- RoFlix: keep game economy server-authoritative.
-- Compatibility: old RPC names stay. Client payloads cannot mint gems/exp/inventory.

begin;

revoke all on table public.roflix_game_stats from anon, authenticated;
grant select on table public.roflix_game_stats to authenticated;

revoke all on table public.roflix_gacha_inventory from anon, authenticated;
grant select on table public.roflix_gacha_inventory to authenticated;

drop policy if exists "gacha inventory own insert" on public.roflix_gacha_inventory;
drop policy if exists "game stats own write" on public.roflix_game_stats;
drop policy if exists "game stats own update" on public.roflix_game_stats;
drop policy if exists "game stats own insert" on public.roflix_game_stats;

create table if not exists public.roflix_watch_reward_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  movie_slug text not null,
  claimed_minutes integer not null check (claimed_minutes > 0 and claimed_minutes <= 15),
  claimed_at timestamptz not null default now()
);
create index if not exists roflix_watch_reward_claims_user_time_idx
  on public.roflix_watch_reward_claims(user_id, claimed_at desc);
alter table public.roflix_watch_reward_claims enable row level security;
revoke all on table public.roflix_watch_reward_claims from anon, authenticated;
grant select on table public.roflix_watch_reward_claims to authenticated;

alter table public.roflix_watch_reward_claims
  add column if not exists claim_bucket timestamptz;
create unique index if not exists roflix_watch_reward_claims_user_bucket_uidx
  on public.roflix_watch_reward_claims(user_id, claim_bucket);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'gems'
  ) then
    execute $fn$
      create or replace function public.roflix_protect_profile_economy()
      returns trigger
      language plpgsql
      security definer
      set search_path = public
      as $t$
      begin
        if tg_op = 'UPDATE' and not public.roflix_is_admin() then
          new.gems := old.gems;
        end if;
        return new;
      end;
      $t$;
    $fn$;
    execute 'drop trigger if exists roflix_profile_economy_guard on public.profiles';
    execute 'create trigger roflix_profile_economy_guard before update on public.profiles for each row execute function public.roflix_protect_profile_economy()';
  end if;
end $$;

-- Watch reward: ignore client minutes/episode flags. 1 minute per eligible call.
-- Global 60s cooldown + 5 minute per-slug cooldown + 240 minutes/day.
create or replace function public.roflix_award_watch(
  p_movie_slug text,
  p_minutes integer default 0,
  p_episode boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  u uuid := auth.uid();
  g public.roflix_game_stats;
  gain integer := 1;
  claimed_today integer;
  new_level integer;
  slug text;
begin
  if u is null then raise exception 'Login required'; end if;
  slug := left(trim(coalesce(p_movie_slug, '')), 180);
  if slug = '' then raise exception 'Movie slug required'; end if;
  if slug !~ '^[A-Za-z0-9][A-Za-z0-9._:-]{1,179}$' then
    return jsonb_build_object('awarded', false, 'reason', 'Invalid movie slug');
  end if;
  if exists (
    select 1 from public.roflix_watch_reward_claims
    where user_id = u and claimed_at > now() - interval '60 seconds'
  ) then
    return jsonb_build_object('awarded', false, 'reason', 'Global watch reward cooldown');
  end if;
  if exists (
    select 1 from public.roflix_watch_reward_claims
    where user_id = u and movie_slug = slug and claimed_at > now() - interval '5 minutes'
  ) then
    return jsonb_build_object('awarded', false, 'reason', 'Watch reward cooldown');
  end if;
  select coalesce(sum(claimed_minutes), 0)::integer
    into claimed_today
    from public.roflix_watch_reward_claims
    where user_id = u and claimed_at >= date_trunc('day', now());
  if claimed_today >= 240 then
    return jsonb_build_object('awarded', false, 'reason', 'Daily watch reward limit reached');
  end if;
  insert into public.roflix_game_stats(user_id) values (u) on conflict (user_id) do nothing;
  insert into public.roflix_watch_reward_claims(user_id, movie_slug, claimed_minutes, claim_bucket)
    values (u, slug, gain, date_trunc('minute', now()))
    on conflict (user_id, claim_bucket) do nothing;
  if not found then
    return jsonb_build_object('awarded', false, 'reason', 'Watch reward cooldown');
  end if;
  update public.roflix_game_stats
    set exp = coalesce(exp, 0) + 2,
        watch_minutes = coalesce(watch_minutes, 0) + gain,
        updated_at = now()
    where user_id = u
    returning * into g;
  new_level := greatest(1, floor(coalesce(g.exp, 0) / 1000) + 1)::int;
  update public.roflix_game_stats
    set level = new_level, updated_at = now()
    where user_id = u
    returning * into g;
  return jsonb_build_object(
    'awarded', true,
    'level', g.level,
    'exp', g.exp,
    'watch_minutes', g.watch_minutes,
    'awarded_minutes', gain
  );
end;
$$;

-- Legacy wallet RPC: never mutates. Returns current server gems so old clients resync.
create or replace function public.roflix_user_adjust_gem(p_delta bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare g bigint;
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  insert into public.roflix_game_stats(user_id) values (auth.uid()) on conflict (user_id) do nothing;
  select coalesce(gems, 0) into g from public.roflix_game_stats where user_id = auth.uid();
  return jsonb_build_object('gems', g, 'mutated', false, 'ignored_delta', coalesce(p_delta, 0));
end;
$$;

-- Legacy sync still ignores client progression fields.
create or replace function public.roflix_sync_game_state(
  p_level integer,
  p_exp bigint,
  p_gems bigint,
  p_gems_earned bigint,
  p_movies_watched bigint,
  p_episodes_watched bigint,
  p_comments_count bigint,
  p_favorites_count bigint,
  p_watch_minutes bigint,
  p_gacha_pulls bigint
)
returns public.roflix_game_stats
language plpgsql
security definer
set search_path = public
as $$
declare r public.roflix_game_stats;
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  insert into public.roflix_game_stats(user_id) values (auth.uid()) on conflict (user_id) do nothing;
  select * into r from public.roflix_game_stats where user_id = auth.uid();
  return r;
end;
$$;

-- Keep legacy Gacha names as a compatibility layer over server-side roll.
create or replace function public.roflix_gacha_commit(
  p_cost bigint,
  p_card_key text,
  p_name text,
  p_movie text,
  p_rarity text,
  p_image text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return public.roflix_gacha_roll(1);
end;
$$;

create or replace function public.roflix_gacha_commit_batch(p_cost bigint, p_cards jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare n integer;
begin
  if jsonb_typeof(coalesce(p_cards, '[]'::jsonb)) <> 'array' then
    raise exception 'Invalid card batch';
  end if;
  n := jsonb_array_length(p_cards);
  if n not in (1, 10) then raise exception 'Invalid Gacha count'; end if;
  return public.roflix_gacha_roll(n);
end;
$$;

create or replace function public.roflix_gacha_merge(p_cards jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Login required'; end if;
  return 0;
end;
$$;

revoke all on function public.roflix_award_watch(text, integer, boolean) from public, anon;
grant execute on function public.roflix_award_watch(text, integer, boolean) to authenticated;

revoke all on function public.roflix_user_adjust_gem(bigint) from public, anon;
grant execute on function public.roflix_user_adjust_gem(bigint) to authenticated;

revoke all on function public.roflix_sync_game_state(integer,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint) from public, anon;
grant execute on function public.roflix_sync_game_state(integer,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint) to authenticated;

revoke all on function public.roflix_gacha_commit(bigint,text,text,text,text,text) from public, anon;
grant execute on function public.roflix_gacha_commit(bigint,text,text,text,text,text) to authenticated;

revoke all on function public.roflix_gacha_commit_batch(bigint, jsonb) from public, anon;
grant execute on function public.roflix_gacha_commit_batch(bigint, jsonb) to authenticated;

revoke all on function public.roflix_gacha_merge(jsonb) from public, anon;
grant execute on function public.roflix_gacha_merge(jsonb) to authenticated;

drop policy if exists "game stats own write" on public.roflix_game_stats;
drop policy if exists "game stats own update" on public.roflix_game_stats;
drop policy if exists "game stats own insert" on public.roflix_game_stats;
drop policy if exists "gacha inventory own insert" on public.roflix_gacha_inventory;

commit;
