begin;

create table if not exists public.roflix_watch_reward_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  movie_slug text not null,
  claimed_minutes integer not null check (claimed_minutes > 0 and claimed_minutes <= 15),
  claimed_at timestamptz not null default now()
);
create index if not exists roflix_watch_reward_claims_user_time_idx on public.roflix_watch_reward_claims(user_id, claimed_at desc);
alter table public.roflix_watch_reward_claims enable row level security;

create or replace function public.roflix_award_watch(p_movie_slug text, p_minutes integer default 0, p_episode boolean default false)
returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid(); g public.roflix_game_stats; gain integer; exp_gain bigint; new_level integer; claimed_today integer;
begin
 if u is null then raise exception 'Login required'; end if;
 if nullif(trim(coalesce(p_movie_slug,'')),'') is null then raise exception 'Movie slug required'; end if;
 gain:=greatest(0,least(15,coalesce(p_minutes,0)));
 if gain=0 then return jsonb_build_object('awarded',false,'reason','No eligible watch time'); end if;
 select coalesce(sum(claimed_minutes),0)::integer into claimed_today from public.roflix_watch_reward_claims where user_id=u and claimed_at>=date_trunc('day',now());
 gain:=least(gain,greatest(0,240-claimed_today));
 if gain<=0 then return jsonb_build_object('awarded',false,'reason','Daily watch reward limit reached'); end if;
 if exists(select 1 from public.roflix_watch_reward_claims where user_id=u and movie_slug=left(trim(p_movie_slug),500) and claimed_at>now()-interval '5 minutes') then return jsonb_build_object('awarded',false,'reason','Watch reward cooldown'); end if;
 insert into public.roflix_game_stats(user_id) values(u) on conflict(user_id) do nothing;
 exp_gain:=gain*2;
 insert into public.roflix_watch_reward_claims(user_id,movie_slug,claimed_minutes) values(u,left(trim(p_movie_slug),500),gain);
 update public.roflix_game_stats set exp=coalesce(exp,0)+exp_gain,watch_minutes=coalesce(watch_minutes,0)+gain,episodes_watched=coalesce(episodes_watched,0)+case when p_episode then 1 else 0 end,updated_at=now() where user_id=u returning * into g;
 new_level:=greatest(1,floor(coalesce(g.exp,0)/1000)+1)::int;
 update public.roflix_game_stats set level=new_level,updated_at=now() where user_id=u returning * into g;
 return jsonb_build_object('awarded',true,'level',g.level,'exp',g.exp,'watch_minutes',g.watch_minutes,'episodes_watched',g.episodes_watched,'awarded_minutes',gain);
end; $$;

create or replace function public.roflix_gacha_commit(p_cost bigint,p_card_key text,p_name text,p_movie text,p_rarity text,p_image text)
returns jsonb language plpgsql security definer set search_path=public as $$ begin return public.roflix_gacha_roll(1); end; $$;

create or replace function public.roflix_gacha_commit_batch(p_cost bigint,p_cards jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare n integer; begin if jsonb_typeof(coalesce(p_cards,'[]'::jsonb))<>'array' then raise exception 'Invalid card batch'; end if; n:=jsonb_array_length(p_cards); if n not in (1,10) then raise exception 'Invalid Gacha count'; end if; return public.roflix_gacha_roll(n); end; $$;

create or replace function public.roflix_gacha_merge(p_cards jsonb)
returns integer language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null then raise exception 'Login required'; end if; return 0; end; $$;

commit;
